network:
  version: 2
  ethernets:
    enp0s8:
      addresses:
       - 192.168.0.66/24
       - 192.168.1.198/32
      nameservers:
        addresses:
          - 8.8.8.8
          - 8.8.4.4
        search: []
      routes:
        - to: 192.168.1.0/24
          via: 192.168.0.65