version: '3'

services:
    cassandra1:
        image: 'cassandra:latest'
        ports:
            - '9042:9042'
        environment:
            - CASSANDRA_CLUSTER_NAME=cluster_test
            - CASSANDRA_SEEDS=cassandra1,cassandra2,cassandra3
            - MAX_HEAP_SIZE=256M
            - HEAP_NEWSIZE=64M
        networks:
            casnet:
                ipv4_address: 192.168.1.200

    cassandra2:
        image: 'cassandra:latest'
        ports:
            - '9043:9042'
        environment:
            - CASSANDRA_CLUSTER_NAME=cluster_test
            - CASSANDRA_SEEDS=cassandra1,cassandra2,cassandra3
            - MAX_HEAP_SIZE=256M
            - HEAP_NEWSIZE=64M
        networks:
           casnet:
                ipv4_address: 192.168.1.201

    cassandra3:
        image: 'cassandra:latest'
        ports:
            - '9044:9042'
        environment:
            - CASSANDRA_CLUSTER_NAME=cluster_test
            - CASSANDRA_SEEDS=cassandra1,cassandra2,cassandra3
            - MAX_HEAP_SIZE=256M
            - HEAP_NEWSIZE=64M
        networks:
            casnet:
               ipv4_address: 192.168.1.202

networks:
    casnet:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet:  "192.168.1.0/24"
                  gateway: "192.168.1.197"